from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
from typing import Iterable

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.config import CONFIG, Config
from src.pipeline import run_project


RAW_TABLES = ("prices", "fundamentals", "universe")
TABLE_SUFFIXES = ("parquet", "csv", "pkl")


def _existing_table_path(raw_dir: Path, name: str) -> Path | None:
    for suffix in TABLE_SUFFIXES:
        path = raw_dir / f"{name}.{suffix}"
        if path.exists():
            return path
    return None


def _read_table(path: Path) -> pd.DataFrame:
    if path.suffix == ".parquet":
        return pd.read_parquet(path)
    if path.suffix == ".pkl":
        return pd.read_pickle(path)
    return pd.read_csv(path)


def _raw_table_status(cfg: Config) -> dict[str, dict]:
    status: dict[str, dict] = {}
    for name in RAW_TABLES:
        path = _existing_table_path(cfg.raw_dir, name)
        if path is None:
            status[name] = {"exists": False, "path": None}
            continue
        row: dict = {"exists": True, "path": str(path), "rows": None, "date_min": None, "date_max": None, "code_count": None}
        try:
            frame = _read_table(path)
            row["rows"] = int(len(frame))
            if "code" in frame.columns:
                row["code_count"] = int(frame["code"].astype(str).nunique())
            for column in ("date", "ann_date", "report_period"):
                if column in frame.columns:
                    dates = pd.to_datetime(frame[column], errors="coerce").dropna()
                    if not dates.empty:
                        row[f"{column}_min"] = str(dates.min().date())
                        row[f"{column}_max"] = str(dates.max().date())
        except Exception as exc:  # pragma: no cover - depends on local data files.
            row["error"] = str(exc)
        status[name] = row
    return status


def _mssql_status() -> dict[str, object]:
    env_keys = sorted(key for key in os.environ if key.startswith("ALPHA_MSSQL_"))
    env_file = ROOT / "config" / "mssql.env"
    return {
        "env_keys_present": env_keys,
        "env_file_exists": env_file.exists(),
        "env_file_path": str(env_file),
    }


def _read_csv_if_exists(path: Path) -> pd.DataFrame | None:
    if not path.exists():
        return None
    return pd.read_csv(path)


def _latex_escape(value: object) -> str:
    text = "" if pd.isna(value) else str(value)
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


def _fmt(value: object, digits: int = 4) -> str:
    if pd.isna(value):
        return ""
    if isinstance(value, int):
        return str(value)
    if isinstance(value, (int, float)):
        return f"{value:.{digits}f}"
    return str(value)


def _latex_rows(frame: pd.DataFrame, columns: Iterable[str], rename: dict[str, str]) -> str:
    rows = []
    for _, row in frame.iterrows():
        values = [_latex_escape(_fmt(row[column])) for column in columns]
        rows.append("    " + " & ".join(values) + r" \\")
    header = "    " + " & ".join(_latex_escape(rename.get(column, column)) for column in columns) + r" \\"
    return "\n".join([header, r"    \midrule", *rows])


def _baseline_latex(frame: pd.DataFrame) -> str:
    cols = ["name", "ic_mean", "ic_ir", "turnover_mean", "net_long_short_mean", "observations"]
    data = frame.copy()
    if "ic_ir" in data.columns:
        data = data.sort_values("ic_ir", ascending=False)
    rows = _latex_rows(
        data[cols],
        cols,
        {
            "name": "因子",
            "ic_mean": "Rank IC",
            "ic_ir": "ICIR",
            "turnover_mean": "换手率",
            "net_long_short_mean": "成本后多空",
            "observations": "样本数",
        },
    )
    return """% Generated by scripts/paper_update_round.py
\\begin{table}[H]
  \\centering
  \\caption{真实数据/当前 raw 数据下的基线因子样本外结果}
  \\label{tab:real-baselines}
  \\begin{tabular}{lccccc}
    \\toprule
""" + rows + """
    \\bottomrule
  \\end{tabular}
\\end{table}
"""


def _factor_latex(frame: pd.DataFrame) -> str:
    cols = ["name", "IC", "ICIR", "turnover", "net_long_short", "max_abs_baseline_corr"]
    data = frame.copy()
    if "ICIR" in data.columns:
        data = data.sort_values("ICIR", ascending=False)
    rows = _latex_rows(
        data[cols],
        cols,
        {
            "name": "候选因子",
            "IC": "Rank IC",
            "ICIR": "ICIR",
            "turnover": "换手率",
            "net_long_short": "成本后多空",
            "max_abs_baseline_corr": "基线相关性",
        },
    )
    return """% Generated by scripts/paper_update_round.py
\\begin{table}[H]
  \\centering
  \\caption{真实数据/当前 raw 数据下的候选因子闭环结果}
  \\label{tab:real-agent-factors}
  \\begin{tabular}{lccccc}
    \\toprule
""" + rows + """
    \\bottomrule
  \\end{tabular}
\\end{table}
"""


def _markdown_status(raw_status: dict[str, dict], mssql: dict[str, object], baseline: pd.DataFrame | None, factors: pd.DataFrame | None) -> str:
    all_raw = all(row.get("exists") for row in raw_status.values())
    source = "raw data files present" if all_raw else "synthetic fallback would be used by the pipeline"
    lines = [
        "# Paper update round status",
        "",
        f"- Data source status: `{source}`",
        f"- MSSQL env file: `{mssql['env_file_path']}` exists = `{mssql['env_file_exists']}`",
        f"- MSSQL env keys in current process: `{', '.join(mssql['env_keys_present']) or 'none'}`",
        "",
        "## Raw tables",
        "",
        "| table | exists | rows | codes | date range | file |",
        "|---|---:|---:|---:|---|---|",
    ]
    for name, row in raw_status.items():
        date_min = row.get("date_min") or row.get("ann_date_min") or row.get("report_period_min") or ""
        date_max = row.get("date_max") or row.get("ann_date_max") or row.get("report_period_max") or ""
        lines.append(
            "| {name} | {exists} | {rows} | {codes} | {date_range} | `{path}` |".format(
                name=name,
                exists=row.get("exists"),
                rows=row.get("rows") or "",
                codes=row.get("code_count") or "",
                date_range=f"{date_min} to {date_max}" if date_min or date_max else "",
                path=row.get("path") or "",
            )
        )
    lines.extend(["", "## Result tables", ""])
    lines.append(f"- Baseline summary rows: `{0 if baseline is None else len(baseline)}`")
    lines.append(f"- Candidate factor summary rows: `{0 if factors is None else len(factors)}`")
    if not all_raw:
        lines.extend(
            [
                "",
                "## Next commands",
                "",
                "```bash",
                "python scripts/mssql_tool.py --env-file config/mssql.env snapshot --output-dir data/metadata/mssql/latest --row-counts",
                "# After field mapping SQL is ready:",
                "python scripts/mssql_tool.py --env-file config/mssql.env export --sql-file sql/export_prices.sql --output data/raw/prices.csv",
                "python scripts/mssql_tool.py --env-file config/mssql.env export --sql-file sql/export_fundamentals.sql --output data/raw/fundamentals.csv",
                "python scripts/mssql_tool.py --env-file config/mssql.env export --sql-file sql/export_universe.sql --output data/raw/universe.csv",
                "python scripts/paper_update_round.py --run-pipeline",
                "```",
            ]
        )
    return "\n".join(lines) + "\n"


def generate_update_outputs(cfg: Config = CONFIG, output_dir: Path | None = None, run_pipeline: bool = False) -> dict[str, str]:
    if run_pipeline:
        run_project(cfg=cfg, rounds=1, per_round=2, include_agent=True)

    out = output_dir or (cfg.results_dir / "paper_update" / "latest")
    out.mkdir(parents=True, exist_ok=True)

    raw_status = _raw_table_status(cfg)
    mssql = _mssql_status()
    baseline = _read_csv_if_exists(cfg.report_dir / "baseline_summary.csv")
    factors = _read_csv_if_exists(cfg.report_dir / "factor_summary.csv")
    raw_ready = all(row.get("exists") for row in raw_status.values())

    manifest = {
        "raw_status": raw_status,
        "mssql": mssql,
        "baseline_summary_path": str(cfg.report_dir / "baseline_summary.csv"),
        "factor_summary_path": str(cfg.report_dir / "factor_summary.csv"),
    }
    (out / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    (out / "status.md").write_text(_markdown_status(raw_status, mssql, baseline, factors), encoding="utf-8")

    if raw_ready:
        latex_parts = []
        if baseline is not None and not baseline.empty:
            latex_parts.append(_baseline_latex(baseline))
        if factors is not None and not factors.empty:
            latex_parts.append(_factor_latex(factors))
        latex_text = "\n".join(latex_parts)
    else:
        latex_text = (
            "% Raw data files are incomplete. Do not paste current result tables into the paper as real-data evidence.\n"
            "% Finish data/raw/prices.*, fundamentals.*, and universe.*, then rerun:\n"
            "% python scripts/paper_update_round.py --run-pipeline\n"
        )
    (out / "latex_tables.tex").write_text(latex_text, encoding="utf-8")
    return {"output_dir": str(out), "status": str(out / "status.md"), "latex": str(out / "latex_tables.tex")}


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Prepare paper update artifacts from current raw data and reports.")
    parser.add_argument("--output-dir", type=Path, default=CONFIG.results_dir / "paper_update" / "latest")
    parser.add_argument("--run-pipeline", action="store_true", help="Run the deterministic pipeline before generating snippets.")
    args = parser.parse_args(argv)
    print(json.dumps(generate_update_outputs(output_dir=args.output_dir, run_pipeline=args.run_pipeline), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
